name: Build PDFs

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./pdf-generator

jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    steps:
    - name: Pull repository files
      uses: actions/checkout@v6

    - name: Load and cache Node
      uses: actions/setup-node@v6
      with:
        node-version: '24'
        cache: 'npm'
        cache-dependency-path: 'pdf-generator/package-lock.json'

    - name: Install Dependencies
      run: npm ci

    - name: Build Constitution
      run: npm run build:constitution

    - name: Build By-Laws
      run: npm run build:bylaws

    - name: Build Policies
      run: npm run build:policies

    - name: Build Ithaka Appendix
      run: npm run build:ithaka

    - name: Archive PDFs
      uses: actions/upload-artifact@v6
      with:
        name: wyc-doc-pdfs-${{ github.run_id }}
        path: |
          *.pdf

    - name: Download PDFs
      uses: actions/download-artifact@v7
      with:
        name: wyc-doc-pdfs-${{ github.run_id }}

    - name: Notify Success
      if: success()
      run: echo "PDF build completed successfully."

    - name: Notify Failure
      if: failure()
      run: echo "PDF build failed. Check the logs for details."
