name: Build and Deploy PDFs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    working-directory: ./pdf-generator

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Pull repository files
      uses: actions/checkout@v6

    # Temporary workaround for Ubuntu 23.10+ AppArmor restrictions
    - name: Enable unprivileged user namespaces
      run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

    - name: Load and cache Node
      uses: actions/setup-node@v6
      with:
        node-version: '24'
        cache: 'npm'
        cache-dependency-path: 'pdf-generator/package-lock.json'

    - name: Install Dependencies
      run: npm ci

    - name: Build all PDFs
      run: npm run build:all

    - name: Stage site for deployment
      run: |
        mkdir -p ../site
        cp ../*.pdf ../site/
        cp ../index.html ../site/
        echo "documents.washingtonyachtclub.org" > ../site/CNAME

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: site

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
